### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by takenori-y** [sp-nitech/SPTK#3]
- [x] support magic number in `mlpg`
- [x] implement `gmm`, `gmmp`
- [x] implement `vc`
- [x] implement `grpdelay`, `phase`
- [x] implement `pqmf`
- [x] make test of all commands
- [x] provide manual of all commands
- [x] update copyright
